<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<IsTestProject>true</IsTestProject>
		<OutputPath>$(SolutionDir)\bin\$(Configuration)\$(AssemblyName)\</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="nunit" Version="3.14.0" />
		<PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Engine\Engine.csproj" />
		<ProjectReference Include="..\EntityComponentSystemCSharp\EntityComponentSystemCSharp.csproj" />
		<ProjectReference Include="..\Contracts\Contracts.csproj" />
		<ProjectReference Include="..\FeatureDetector\FeatureDetector.csproj" />
	</ItemGroup>
</Project>
